language: python
python:
- 3.8
install:
- pip install -U tox-travis
- pip install -r requirements.txt
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: skyme5
  on:
    repo: skyme5/magzdb
    python: 3.8
  password: $PYPI_PASS
after_success:
- codecov
